#=
Reads results.json (written by model.jl) and writes post.md: the actual
blog post, with every number sourced from that file - nothing here is
typed in by hand.

Run after model.jl:
    julia --project=examples/usecases examples/usecases/01-beer-game/generate_post.jl
=#
using JSON3

results = open(joinpath(@__DIR__, "results.json")) do io
    JSON3.read(io)
end

pct(x) = string(round(x * 100; digits=1), "%")
fmt(x; digits=1) = round(x; digits=digits)
ratio(x; digits=1) = string(round(x; digits=digits), "x")

naive = results.naive_aggregate
opt_in = results.optimized_in_sample_aggregate
opt_hold = results.optimized_holdout_aggregate
s1 = results.optimized_in_sample_scenario1

# Converted to plain Dict{String,Float64} rather than indexed as JSON3
# objects directly - guarantees String-key getindex regardless of JSON3's
# own Symbol/String indexing support.
as_dict(obj) = Dict(string(k) => Float64(v) for (k, v) in pairs(obj))

naive_bw = as_dict(results.naive_bullwhip_ratios)
opt_bw = as_dict(results.optimized_bullwhip_ratios)
naive_cv = as_dict(results.naive_inventory_cv)
opt_cv = as_dict(results.optimized_inventory_cv)

fill_rate_change_pp = round((opt_in.fill_rate - naive.fill_rate) * 100; digits=2)
generalization_gap_pp = round((opt_in.fill_rate - opt_hold.fill_rate) * 100; digits=2)

cover2 = join(round.(Float64.(results.tuned_policy_cover.l2_wholesaler_to_retailer); digits=2), ", ")
cover3 = join(round.(Float64.(results.tuned_policy_cover.l3_factory_to_wholesaler); digits=2), ", ")
cover4 = join(round.(Float64.(results.tuned_policy_cover.l4_supplier_to_factory); digits=2), ", ")

post = """
# The Beer Game, "Solved"? What an Optimizer Actually Did to the Bullwhip Effect

*Part of a series on SupplyChainSimulation.jl and SupplyChainOptimization.jl. All numbers on this page are generated by running [`model.jl`](model.jl) in CI — see the workflow run linked in this repo's Actions tab for the raw log.*

## The game that's been humbling smart people for 60 years

In 1961, MIT's Jay Forrester built a simple board-game simulation of a four-stage supply chain — retailer, wholesaler, factory, supplier — each stage separated by a shipping delay, each stage only able to see its own orders and inventory. Consumer demand barely moves. And yet, run after run, for six decades, the orders placed *inside* the chain oscillate wildly.

This isn't a fluke of bad players. John Sterman's 1989 study in *Management Science* ("Modeling Managerial Behavior: Misperceptions of Feedback in a Dynamic Decision-Making Experiment") ran the game with people who *understood* the dynamics going in, and they still produced the same oscillation. Lee, Padmanabhan, and Whang's 1997 analysis of the same pattern in real companies (built on Procter & Gamble's own study of Pampers demand) gave it a name and a rough shape: consumer demand that varies ±5–10% can show up as ±20% swings at the retailer, ±40% at the wholesaler, ±80%+ at the manufacturer. That amplification — the **bullwhip effect** — is measured, formally, as the ratio of the variance of what an echelon orders to the variance of what its actual downstream customer demands. Ratio above 1: this echelon is amplifying. Below 1: it's damping.

We built the same four-echelon network in SupplyChainSimulation.jl, measured that ratio directly at every echelon, and let `optimize!` tune the upstream ordering policies. The result is more interesting — and more useful — than "the optimizer fixed it."

## The network

Four echelons — customer, retailer, wholesaler, factory, supplier — with 2-period lead times between retailer/wholesaler/factory and a 4-period lead time from the supplier, demand averaging $(results.mean_demand) units/period, simulated over a $(results.horizon)-period horizon across $(results.scenario_count) independent stochastic demand scenarios (Poisson($(results.mean_demand))). Full network-construction code is in [`model.jl`](model.jl); it's the same network shape as the package's own `test/policy-beergame-tests.jl`.

## Baseline: a naive fixed policy already bullwhips, textbook-style

Each upstream echelon runs `NetUptoOrderingPolicy`, reacting only to its own local net inventory, with a fixed target sized for "pipeline coverage, no safety stock" — mean demand × (lead time + 1) — and never tuned:

| Lane | Lead time | Naive target |
|---|---|---|
| wholesaler → retailer | 2 | $(results.naive_targets.l2_wholesaler_to_retailer) |
| factory → wholesaler | 2 | $(results.naive_targets.l3_factory_to_wholesaler) |
| supplier → factory | 4 | $(results.naive_targets.l4_supplier_to_factory) |

Run across the $(results.scenario_count) scenarios:

| Metric | Value |
|---|---|
| Total demand | $(fmt(naive.total_demand)) units |
| Units sold | $(fmt(naive.total_sales)) |
| Lost sales | $(fmt(naive.total_lost_sales)) units |
| **Fill rate** | **$(pct(naive.fill_rate))** |

And the bullwhip ratio (Var(orders placed)/Var(customer demand)) at each echelon, averaged across all $(results.scenario_count) scenarios:

| Echelon | Bullwhip ratio |
|---|---|
| Retailer's orders (→ wholesaler) | $(ratio(naive_bw["retailer_orders (l2)"])) |
| Wholesaler's orders (→ factory) | $(ratio(naive_bw["wholesaler_orders (l3)"])) |
| Factory's orders (→ supplier) | $(ratio(naive_bw["factory_orders (l4)"])) |

That's the textbook shape exactly: mild amplification at the retailer, worse at the wholesaler, worst at the factory — the pain compounds the further you are from the actual customer.

## What the optimizer finds — and it's not what you'd expect

Same network, same $(results.scenario_count) scenarios, but the three upstream echelons now run `BackwardCoverageOrderingPolicy`, tuned jointly by `optimize!` against one shared cost function (lost sales + holding + transportation + order costs):

| Metric | Naive | Optimized (same scenarios) |
|---|---|---|
| Fill rate | $(pct(naive.fill_rate)) | $(pct(opt_in.fill_rate)) |
| Lost sales | $(fmt(naive.total_lost_sales)) units | $(fmt(opt_in.total_lost_sales)) units |

Fill rate got *worse* — $(fill_rate_change_pp) percentage points worse — not better. And the bullwhip ratios:

| Echelon | Naive | Optimized |
|---|---|---|
| Retailer's orders | $(ratio(naive_bw["retailer_orders (l2)"])) | **$(ratio(opt_bw["retailer_orders (l2)"]))** |
| Wholesaler's orders | $(ratio(naive_bw["wholesaler_orders (l3)"])) | **$(ratio(opt_bw["wholesaler_orders (l3)"]))** |
| Factory's orders | $(ratio(naive_bw["factory_orders (l4)"])) | **$(ratio(opt_bw["factory_orders (l4)"]))** |

The optimized policy's order quantities swing with roughly **$(ratio(opt_bw["retailer_orders (l2)"])) to $(ratio(opt_bw["factory_orders (l4)"])) times the variance of actual customer demand** — an order of magnitude worse than the naive policy's already-textbook bullwhip, and, unlike the naive case, it's severe at *every* echelon rather than escalating upstream. For scenario 1 specifically (directly comparable to the repo's own `beer_game()` test, which asserts exactly `lost_sales == 103.0 && sales == 1828.0 && demand == 1931.0`): this run produced lost sales = $(fmt(s1.total_lost_sales)), sales = $(fmt(s1.total_sales)), demand = $(fmt(s1.total_demand)) — matching the known-good value, so this isn't a bug in this analysis; it's what that policy actually does.

The tuned parameters `optimize!` found (`BackwardCoverageOrderingPolicy.cover`, applied per `Policy.jl` as: target net inventory = (last period's order) × (cover[1]+cover[2]) + cover[2]):

| Lane | Tuned `cover` | Implied rule |
|---|---|---|
| wholesaler → retailer | [$(cover2)] | targets ≈ $(round(Float64(results.tuned_policy_cover.l2_wholesaler_to_retailer[1]) + Float64(results.tuned_policy_cover.l2_wholesaler_to_retailer[2]); digits=1)) × last period's order — a hard trend-chaser |
| factory → wholesaler | [$(cover3)] | targets ≈ $(round(Float64(results.tuned_policy_cover.l3_factory_to_wholesaler[1]) + Float64(results.tuned_policy_cover.l3_factory_to_wholesaler[2]); digits=2)) × last period's order — much gentler |
| supplier → factory | [$(cover4)] | first coefficient ≈ 0 — barely reacts to order history at all, runs closer to a flat, thin-buffer order-up-to rule |

So this isn't one uniform mechanism copy-pasted three times — the optimizer found three structurally different rules (an aggressive trend-chaser, a gentle one, and one that mostly ignores the backward-looking signal) that happen to converge on similarly severe order-variance amplification. That convergence is itself worth flagging as something we don't have a single clean explanation for yet, and a good target for a follow-up post that looks at period-by-period order traces instead of aggregate variance ratios.

## So who's actually damping the swings — if anyone?

This is the real question, and the honest answer is: **nobody is damping the order stream.** All three echelons pass through similarly enormous amplification (roughly $(ratio(opt_bw["wholesaler_orders (l3)"])) to $(ratio(opt_bw["retailer_orders (l2)"]))), instead of the naive case's clean upstream escalation. But the *inventory* picture tells a different story — the coefficient of variation (std/mean) of each node's own on-hand inventory:

| Node | Naive inventory CV | Optimized inventory CV |
|---|---|---|
| Retailer | $(round(naive_cv["retailer"]; digits=2)) | $(round(opt_cv["retailer"]; digits=2)) |
| Wholesaler | $(round(naive_cv["wholesaler"]; digits=2)) | $(round(opt_cv["wholesaler"]; digits=2)) |
| Factory | $(round(naive_cv["factory"]; digits=2)) | $(round(opt_cv["factory"]; digits=2)) |

Under the optimized policy, inventory volatility still climbs upstream just like classic bullwhip theory predicts — it's the **factory**, furthest from the actual customer and behind the longest (4-period) lead time, that ends up carrying the most erratic buffer. So the variance doesn't get *smoothed* anywhere in this system; it gets *warehoused*, and it's warehoused worst at the node with the least direct visibility into real demand — which is exactly the node the original bullwhip literature identifies as the classic victim.

## Why the optimizer is fine with this

Nothing is wrong with the optimizer. It's doing exactly what it was asked to do: minimize `-sales + lost_sales + holding_costs + transportation_costs + 0.001 × orders`. Look at what's *missing* from that list: nothing charges a penalty for an echelon's order quantity swinging wildly from one period to the next. Holding cost here is cheap (0.1 per unit per period) and the order-quantity term is nearly free (0.001 per unit). Given those weights, a policy that reacts hard and fast to the latest signal can track demand well enough to avoid much *additional* lost sales, and the extra inventory volatility that reactiveness creates barely costs anything to hold. The optimizer had no reason to prefer a smooth, boring policy over a jumpy, aggressive one — so it didn't find one. This is a direct, mechanical illustration of a general rule for this whole platform: **the "optimal" policy is optimal only with respect to the costs you actually told it about.** Order-quantity stability is a real cost in the real world; here, it was worth $(round(0.001; digits=3)) per unit, i.e. essentially zero.

## Can this be replicated in a real supply chain? Why, and why not.

**Why not, mostly:**

1. **A ~$(ratio(opt_bw["retailer_orders (l2)"])) order-variance swing is not something a real operation can execute for free**, even if a cost function says it's cheap. Trucking capacity is booked in advance. Production lines have changeover costs and minimum run lengths. A supplier asked to ship 30x more or less than usual with no forward notice will build in padding, refuse, or renegotiate the contract — none of which this simulation's unconstrained, infinite-throughput supplier node has to deal with.
2. **The holding-cost model is linear and flat.** A factory whose inventory coefficient of variation is $(round(opt_cv["factory"]; digits=2)) faces real working-capital, warehouse-capacity, and obsolescence risk that a constant `$0.10 per unit per period` charge doesn't capture. In practice, that volatility has a cost this model is blind to.
3. **This is still a centralized result.** `optimize!` set all three echelons' rules jointly, with one shared objective. Even a company willing to tolerate this much internal volatility would need the automation and cross-echelon authority to execute it without every swing triggering a manual override from whoever's job it is to explain a tripled order to their boss.

**Why it's still worth knowing:** it's a sharper, more useful result than "the optimizer solves the bullwhip" would have been. It shows precisely how sensitive an "optimal" ordering policy is to the cost assumptions it's handed — change the weight on order-quantity stability, or cap the supplier's throughput, and you'd likely get a genuinely different, smoother policy. That's a concrete, testable next experiment (a natural Part 2: sweep an order-change penalty and a supplier capacity constraint, and see what it takes to get a policy that's both cheap *and* operationally sane) rather than a vague caveat.

## The generalization check

The optimized policy above was tuned on $(results.scenario_count) scenarios seeded at $(results.calibration_seed). Running that *exact same, already-tuned* policy — no re-optimization — against a fresh batch of $(results.scenario_count) scenarios it never saw (seed $(results.holdout_seed), same demand distribution) gives:

| Metric | In-sample (tuned on this data) | Out-of-sample (fresh scenarios) |
|---|---|---|
| Fill rate | $(pct(opt_in.fill_rate)) | $(pct(opt_hold.fill_rate)) |
| Lost sales | $(fmt(opt_in.total_lost_sales)) units | $(fmt(opt_hold.total_lost_sales)) units |

Gap: **$(generalization_gap_pp) percentage points**, entirely sampling noise since both batches are drawn from the identical Poisson($(results.mean_demand)) process — this is a floor, not a worst case. But given what the bullwhip numbers above actually show, distributional generalization isn't the most important robustness question for this policy. **Sensitivity to the cost weights themselves** — what happens to the tuned policy, and its bullwhip ratios, as the order-quantity penalty or the holding-cost rate change — is the more important test, and it's the one this run doesn't answer yet.

## Try it yourself

The full script that produced every number on this page is [`model.jl`](model.jl) in this directory; the [SupplyChainSimulation.jl docs](https://SupplyChef.github.io/SupplyChainSimulation.jl/dev) walk through the same network shape from first principles (EOQ → safety stock → beer game).

---
*Sources: Sterman, J.D. (1989), "Modeling Managerial Behavior: Misperceptions of Feedback in a Dynamic Decision-Making Experiment," Management Science 35(3). Lee, H.L., Padmanabhan, V., Whang, S. (1997), "The Bullwhip Effect in Supply Chains," Sloan Management Review / "Information Distortion in a Supply Chain: The Bullwhip Effect," Management Science 43(4) — the Var(orders)/Var(demand) bullwhip ratio used throughout this page is their standard definition.*
"""

open(joinpath(@__DIR__, "post.md"), "w") do io
    write(io, post)
end

println("Wrote post.md")
