name: Profile

on:
  workflow_dispatch:

env:
  JULIA_PKG_SERVER_REGISTRY_PREFERENCE: conservative

jobs:
  profile:
    name: CPU profile - beer_game()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
          arch: x64
      - run: julia --project=benchmark -e 'using Pkg; Pkg.instantiate()'
      - run: julia --project=benchmark benchmark/profile_beergame.jl
      - run: julia --project=benchmark benchmark/profile_beergame_direct.jl
